### ISSUE TITLE
Instant Search Results appearing on product pages when Autocomplete is off

### ISSUE THREAD

**Issue by bslinger** [algolia/algoliasearch-magento#302]
While testing the plugin I came across an issue where the Instant Search Results block would replace the page when going to a product page. I tracked it down to line 417 of topsearch.phtml:

`if (algoliaConfig.instant.enabled && (algoliaConfig.isSearchPage || !algoliaConfig.autocomplete.enabled))`

which ends up doing the instant search replacement if instant is enabled and autocomplete is not, regardless of the page.

I've removed the last if clause in my local version which resolves the issue, but I'm not sure if that will have any unintended effects.

**Comment by maxiloc** [comment]
@bslinger Are you using the last version 1.5.2 ? because we fixed an issue related to this in this last release

**Comment by maxiloc** [comment]
@bslinger Closing this, feel free to re-open it if needed

**Comment by bslinger** [comment]
We are still having this problem in version 1.5.5. Here is an example page where it is occurring (you will have to visit with a mobile user-agent): http://www.costumes.com.au/dc-comics-wonder-woman-child-girl-s-costume-45729.html

There is a "Refine" block added at the bottom of the page that doesn't do anything, and if you type in the search box, the main page content gets replaced with the search results.

We have instant search on (because we want to use it on search pages, and soon category pages), but autocomplete off on the mobile version of the site.

**Comment by bslinger** [comment]
I've had to put a fix in place on our site so you won't see the issue there anymore - as before I've commented out the "!algoliaConfig.autocomplete.enabled" clause and it seems to behave correctly.

**Comment by JanPetr** [comment]
Hello @bslinger,
I checked and it's expected behaviour from our extension. When you have autocomplete turned off and instant search turned on, each keystroke on search input on every page should trigger instant search. So even when you are on the detail of a product and start typing search query, the main page content should be replaced by results. We are aiming for similar experience as you can see for example here: https://jadopado.com/

If you need different behavior it's completly fine to update your JS files to achive desired functionality for your use case.

Anyway, thank you for your issue. We will fix the empty "Refine" block, that is a bug.

**Comment by bslinger** [comment]
Ahh, I see what you're going for, I hadn't realised that was desired functionality because I hadn't seen it working that way on a full size site. We'll probably make use of that for our main site actually, and I'll just disable it for mobile. Might be nice to have that as a configurable option at the store leve.
