### ISSUE TITLE
Configurable product: Simple products (children) SKU's not searchable

### ISSUE THREAD

**Issue by spiralmedia-rupert** [algolia/algoliasearch-magento#354]
I've had a look through old issues but couldn't find an answer.

Basically, when searching for SKU's belonging to simple products that make up a configurable product no results are show. All the simple's are set to be 'not visible individually'. Is there a work around for this?

Thank you

**Comment by maxiloc** [comment]
Which version of the extension are you using ?

**Comment by spiralmedia-rupert** [comment]
1.5.3

**Comment by maxiloc** [comment]
Yes my bad, it has been fixed with https://github.com/algolia/algoliasearch-magento/pull/340/files,
but it's not yet released.
We are going to make one release this week, until then you can make the change manually

**Comment by spiralmedia-rupert** [comment]
awesome. Thanks Maxiloc

**Comment by spiralmedia-rupert** [comment]
I've applied the patch, removed all indices from algolia.com, reindexed the website and its still not working. Am I missing something else? Another patch that works with this one?

**Comment by spiralmedia-rupert** [comment]
Looks like even configurable product SKU's are not being indexed now.

**Comment by maxiloc** [comment]
Can you try to investigate why ? It's working fine on my side

**Comment by spiralmedia-rupert** [comment]
Sorry Max. Such a Noob, I copied it incorrectly. Thank you so much for your help.
