### ISSUE TITLE
Live search results different than search page results

### ISSUE THREAD

**Issue by greatwitenorth** [algolia/algoliasearch-magento#705]
When I start typing in the search bar I see a list of results show below. But when I hit enter, the search page show a different set of results. I have live search turned off. I can confirm that the request is made to algolia when the search page is loaded. It seems though that it's not using the returned results from algolia.

Magento 1.9.3.1
Algolia 1.7.2

**Comment by JanPetr** [comment]
Hello @greatwitenorth,
thanks for the report.

It's because of Magento 1.9.3 incompatible changes to fulltext search. It's already fixed in #688 and it will be part of the next release.

**Comment by greatwitenorth** [comment]
I'm still seeing this issue running algolia 1.9.0 and Magento 1.9.3.1. The only way I can get algolia to show it's results on the search page is if I enable "Instant Search Results Page". But I don't want the instant results page. I just want my standard results page being populated by products returned by Algolia.

**Comment by JanPetr** [comment]
Hello @greatwitenorth,
​
​so I took a look and tried to investigate your issue.
I'm not able to reproduce on my side. When I search, all products are coming back in the right order.
​
​When I took a look on your website, the products fetched from Algolia and displayed on the result page are the same. They are just displayed in a wrong order on the result page.
​Don't you use any other extension what might affect the order of results?
​Are you able to dive in a code and check if the products from Algolia are correctly sorted [here](https://github.com/algolia/algoliasearch-magento/blob/master/app/code/community/Algolia/Algoliasearch/Model/Resource/Fulltext/Collection.php#L88)?
​
​Let me know.

**Comment by JanPetr** [comment]
Hello @greatwitenorth, did you manage to fix the issue? Is everything alright now?

I'm closing the issue, but if the problem persists, feel free to reopen.

**Comment by greatwitenorth** [comment]
It ended up being an issue with the Amasty sorting plugin. We disabled it and now the search page results are showing correctly.

**Comment by JanPetr** [comment]
Perfect, thanks for letting me know @greatwitenorth. Happy searching! 💯
